name: Publish Website to CPanel
on:
  push:
    branches:
      - main
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
<<<<<<< HEAD

=======
      with:
        fetch-depth: 2 
    - name: Build assets
      run: npm install && npm run build
>>>>>>> e59211df550fec9dce355994f9edb2b5730f7478

    - name: Install PHP and Composer
      uses: shivammathur/setup-php@v2
      with:
          php-version: '7.3' # Adjust to match the PHP version used by your Laravel project
          tools: 'composer'

    - name: Install PHP dependencies
      run: composer install --no-dev --optimize-autoloader
<<<<<<< HEAD

=======
        
>>>>>>> e59211df550fec9dce355994f9edb2b5730f7478
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.SERVER }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
